
export const ALL_LIST='ALL_LIST';
export const ALL_LIST_SAGA='ALL_LIST_SAGA';

export const ADD_LIST='ADD_LIST';
export const ADD_LIST_SAGA='ADD_LIST_SAGA';

export const EDIT_LIST='EDIT_LIST';
export const EDIT_LIST_SAGA='EDIT_LIST_SAGA';

export const DELETE_LIST='DELETE_LIST';
export const DELETE_LIST_SAGA='DELETE_LIST_SAGA';

export const IS_VISIBLE_ADD_TO_DO_IN_LIST='IS_VISIBLE_ADD_TO_DO_IN_LIST';
export const IS_VISIBLE_ADD_TO_DO_IN_LIST_SAGA='IS_VISIBLE_ADD_TO_DO_IN_LIST_SAGA';

export const SET_ID_FOR_ADDING_TO_DO='SET_ID_FOR_ADDING_TO_DO';
export const SET_ID_FOR_ADDING_TO_DO_SAGA='SET_ID_FOR_ADDING_TO_DO_SAGA';


export const ADD_TO_DO_IN_LIST='ADD_TO_DO_IN_LIST';
export const ADD_TO_DO_IN_LIST_SAGA='ADD_TO_DO_IN_LIST_SAGA';
